### ISSUE TITLE
net worth historical chart values appears too low

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#135]
The values in the historical networth chart all appear much too low. I did not troubleshoot in detail, but maybe it's due to missing stock prices on some days and the values going to zero?
Maybe showing the max and min value for each year, along with that date in the chart would help debug this?

**Comment by clovett** [comment]
The historical networth depends on accurate stock holding records back in time.  I have verified in my own records that the prices computed for MSFT stock for the historical net worth match the portfolio reports and my Fidelity statements back 10 years.  

Are yo saying your portfolio reports are also showing the wrong historical values when you edit the "Date" field at the top of the report?  Because the historical networth uses the exact same calculation code as the portfolio reports.

I have not verified it does the right thing on Loan accounts.  Asset accounts (like a house) depend on having the correct history available in the account.  

You can verify your historical records one stock at a time using "View Securities", right click the stock "View Related Transactions".  Check the "Holding" column, if this doesn't match your statements then the net worth and portfolio report will be wrong.

**Comment by andreva7** [comment]
When I select a specific date the report looks to be working fine (I've only checked a few dates)
It's the new bar graph that spans the previous 10+ years that is significantly off.

-Andre

**Comment by clovett** [comment]
Very strange, the Networth report uses the same computation as the portfolio report and simply adds bank account, asset account and loan account balances.  The report shows various rows in the summary table, can you identify which row is off?

**Comment by andreva7** [comment]
Which day of the year is used in the bar graph across the many years?

-Andre

**Comment by andreva7** [comment]
This is the graph that is wrong: My networth did not double from 2022 to 2024, eventhough Microsoft did really well 😊

***@***.***

From: Andre Vachon
Sent: Monday, December 30, 2024 3:53 PM
To: MoneyTools/MyMoney.Net ***@***.***>; MoneyTools/MyMoney.Net ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [MoneyTools/MyMoney.Net] net worth historical chart values appears too low (Issue #135)

Which day of the year is used in the bar graph across the many years?

-Andre

**Comment by andreva7** [comment]
The tooltip fix is good. So the bar graph I have is Dec 30th on all the previous years.

The further back I look, to more off the networth value appears to be.
The bar for 2022 is about 30% off
When I look at the 2008 bar,  it’s off by 20x.
Now if I type in 12-30-2008 and update the report, then number for that day appears to be correct

-Andre

From: Andre Vachon
Sent: Monday, December 30, 2024 3:56 PM
To: 'MoneyTools/MyMoney.Net' ***@***.***>; 'MoneyTools/MyMoney.Net' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [MoneyTools/MyMoney.Net] net worth historical chart values appears too low (Issue #135)

This is the graph that is wrong: My networth did not double from 2022 to 2024, eventhough Microsoft did really well 😊

***@***.***

From: Andre Vachon
Sent: Monday, December 30, 2024 3:53 PM
To: MoneyTools/MyMoney.Net ***@***.***>; MoneyTools/MyMoney.Net ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [MoneyTools/MyMoney.Net] net worth historical chart values appears too low (Issue #135)

Which day of the year is used in the bar graph across the many years?

-Andre

**Comment by clovett** [comment]
Oh, I think I see the issue now also, thanks, I'm investigating...

**Comment by clovett** [comment]
Ok, should be fixed in https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.38

**Comment by andreva7** [comment]
Looks good! Thanks

**Comment by clovett** [comment]
One more teak should get the gap even closer.  It now always includes closed accounts (doesn't try and optimize them out) but then you need to make sure closed accounts end with a zero balance and it now pins each date to midnight so you don't get different numbers throughout the day.

See https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.39

**Comment by andreva7** [comment]
Awesome!

**Comment by andreva7** [comment]
repasting stock quotes without the tag markers

    StockQuote Date="2024-01-04T00:00:00" Open="370.67001" Close="367.94000" High="373.10001" Low="367.17001" Volume="20901500" Downloaded="2024-12-31T14:53:06.3201414-08:00" 
    StockQuote Date="2024-01-05T00:00:00" Open="368.97000" Close="367.75" High="372.059998" Low="366.5" Volume="20987000" Downloaded="2024-12-31T14:53:06.3201402-08:00" 
    StockQuote Date="2024-01-08T00:00:00" Open="369.29999" Close="374.69000" High="375.20001" Low="369.010010" Volume="23134000" Downloaded="2024-12-31T14:53:06.3201392-08:00" 
    StockQuote Date="2024-01-09T00:00:00" Open="372.010010" Close="375.79001" High="375.98999" Low="371.19000" Volume="20830000" Downloaded="2024-12-31T14:53:06.3201381-08:00"

**Comment by clovett** [comment]
Ok, so the .xml file is correct (skipping the weekend of 2024-01-06 and 2024-01-07, but the portfolio report is picking up bogus numbers for those 2 days from somewhere.  So can you check if you have some MSFT add/buy/sell/remove transactions on 2024-01-06 and 2024-01-07 that have a bad MSFT price associated with them?

**Comment by clovett** [comment]
I pushed a fix that makes it so that existing transaction unit prices are ignored in favor of the downloaded stock prices.
See https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.42

**Comment by andreva7** [comment]
The problem disappeared again, without having downloaded your updated version.

Very very weird ...

-Andre

**Comment by andreva7** [comment]
The issue is back (although a tiny bit different. I am running the latest version .42

I start with the networth report.
Then I click on the Taxable Assets -> equities
I set the date to 2024 -01-06 -> It says  440 shares of amazon at a price of 145.24
I set the date to 2024 -01-07 -> It says  440 shares of amazon at a price of 3177.00
I set the date to 2024 -01-08 -> It says  440 shares of amazon at a price of 149.10

This problem always appears correlated to the date being today minus one year.

The last time I bought\sold Amazon stock is 2020

**Comment by andreva7** [comment]
...And the xml file

StockQuote Symbol="AMZN" Date="2024-01-05T00:00:00" Open="144.69000" Close="145.24001" High="146.59000" Low="144.53000" Volume="45124800" Downloaded="2024-12-31T14:52:53.4930625-08:00" 
StockQuote Symbol="AMZN" Date="2024-01-08T00:00:00" Open="146.74001" Close="149.10001" High="149.39999" Low="146.14999" Volume="46757100" Downloaded="2024-12-31T14:52:53.493059-08:00"

**Comment by andreva7** [comment]
I built my version and did some debugging.
I got here, which is where things appear to be interesting.

![image](https://github.com/user-attachments/assets/ee6b910d-1a35-4dc9-86bc-2eab709e291d)

**Comment by andreva7** [comment]
and we get here a few statements later

![image](https://github.com/user-attachments/assets/7b03f50e-a05e-41bf-85e7-7bf53a6e7a82)

**Comment by clovett** [comment]
Ah, I found the bug, there was a load order problem with how the stock quote history was being loaded, and it was not loaded quick enough so the low MSFT stock price was copied from your transactions.  Did you check your transactions, I'm curious what you have on MSFT around 1/5/2024 and 1/6/2024, I'm hoping your transactions records have not recorded a bogus MSFT unit price on those dates. Please try https://github.com/MoneyTools/MyMoney.Net/releases/tag/2.1.0.43

**Comment by andreva7** [comment]
I have no MSFT transactions that I can find during that time, but I'll look some more.

With the latest version the bug I reported no longer repros. So we can call this fixed!

But I'll keep looking for that weird MSFT price.

Thanks.

-Andre

**Comment by clovett** [comment]
Excellent, thanks for pushing for the right fixes.
